### PR TITLE
EFL & Elementary 1.17.1

### PR DESCRIPTION
**Pull request by matsbtegner**
efl and elementary 1.17.1

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Thanks for the updates, but how are you updating these? It seems that you keep adding new files and that your base branch is not synced with master ...

**Comment by matsbtegner** [comment]
On 2016-05-25 15:08, Ryan P.C. McQuen wrote:

> Thanks for the updates, but how are you updating these? It seems that you keep adding new files and that your base branch is not synced with master ...

I might have made a mistake. I made local changes to the .info-files and
uploaded them to my github. Is there another method?

Mats

**Comment by ryanpcmcquen** [comment]
So you can either use `git` (from the command line) and [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) on to my remote first, or just edit the files using GitHub's web editor (clicking the :pencil2:).

If you aren't familiar with `git`, then the latter is probably a bit easier.

**Comment by matsbtegner** [comment]
On 2016-05-25 15:25, Ryan P.C. McQuen wrote:

> So you can either use `git` (from the command line) and [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) on to my remote first, or just edit the files using GitHub's web editor (clicking the :pencil2:).
> 
> If you aren't familiar with `git`, then the latter is probably a bit easier.

Thanks, I'm not that familiar with 'git', Minor edits via the web
interface is probably easier.

**Comment by ryanpcmcquen** [comment]
I made a short gif that may be helpful. :smile_cat:

editing_files_using_the_github_web_interface

**Pull request closed without merging**
